FROM node:lts-alpine

# install simple http server for serving static content
# RUN npm install -g http-server

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .


# build app for production with minification
# RUN npm run build

EXPOSE 8080

CMD npm run serve

# EXPOSE 8080
# CMD [ "http-server", "dist" ]
