version: '3'
services:
    client:
        build: ./client
        ports:
        - "5000:8080"
        volumes:
          - /node_dir/node_modules # isolate node_modules for compatible os
          - ./source:/node_dir/source
